export const projects = [
  {
    slug: "cybershield",
    num: "01",
    name: "CyberShield",
    tag: "Research Project · Final Year",
    date: "Sep 2025 – May 2026",
    problemSolved:
      "Addressed the lack of accessible, Pakistan-focused cybersecurity training by enabling users to learn, practice, and report phishing through multilingual, simulation-based modules.",
    description:
      "Developed in a team of 3, delivering end-to-end platform functionality including role-based dashboards, multi-vector phishing simulations integrating a trained CNN-BiLSTM model, unified probability scoring, and analytics.",
    stack: [
      "Next.js", "TypeScript", "Node.js", "ExpressJS", "MongoDB Atlas",
      "Clerk", "AWS", "Twilio", "Gemini API", "ElevenLabs",
      "Cloudinary", "Vercel", "ML Pipelines", "Deep Learning", "Git", "Nodemailer",
    ],
    achievement: "3rd Best Industry Project · NUST Open House 2026 (40+ teams)",
    achievements: [
      "3rd Best Industry Project · NUST Open House 2026 (40+ teams)",
      "Shortlisted for Rector's Gold Medal Presentation",
      "AI, Cyber Hackathon & Drone Swarm Gala · 20+ participating teams",
    ],
    github: "https://github.com/mkhan429419/Cybershield-Backend",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_cant-believe-our-final-year-project-journey-ugcPost-7460965918576373760-iCfE/",
    image: "/projects/cybershield.png",
    video: "https://www.youtube.com/embed/QSg4ZHYFzHY",
    screenBg: "linear-gradient(135deg, #0a1f14 0%, #0f2e1e 50%, #061a10 100%)",
    accent: "#22C55E",
  },
  {
    slug: "cortex",
    num: "02",
    name: "Cortex Dashboard",
    tag: "Headstarter Hiring Hackathon 2 · 60+ users",
    date: "Aug 2024",
    problemSolved:
      "Developed a system to help car dealerships visualize performance, manage customer profiles, and analyze sentiment in one place.",
    description:
      "Built a performance dashboard to track customer stats, using AWS Comprehend to analyze customer sentiment collected from dynamic customer feedback pages — developed in a team of 3 fellows.",
    stack: [
      "Next.js", "AWS DynamoDB", "TypeScript", "Tailwind",
      "MagicUI", "Clerk", "AWS Comprehend", "Nodemailer", "Vercel",
    ],
    achievement: "Finalist · PAM Track · Headstarter Hackathon 2",
    achievements: ["Finalist · PAM Track · Headstarter Hackathon 2"],
    github: "https://github.com/kambohdiv/car-ai-agent",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_thrilled-to-unveil-cortex-dashboard-our-activity-7233601814137344000-4PRH",
    image: "/projects/cortex.png",
    video: "https://www.youtube.com/embed/euFF9IhDrTs",
    screenBg: "linear-gradient(135deg, #080e1c 0%, #0d1a35 50%, #050b18 100%)",
    accent: "#3B82F6",
  },
  {
    slug: "profeval",
    num: "03",
    name: "ProfEval",
    tag: "Headstarter AI Project · 25+ users",
    date: "Sep 2024",
    problemSolved:
      "Built a chatbot to help students find the perfect professor using RateMyProfessors reviews.",
    description:
      "Built a RAG AI chatbot using the Groq LLaMA 8b model, integrated search by various categories (name, dept, school), and added real-time data scraping via Scraper API & Cheerio.",
    stack: [
      "Next.js", "TypeScript", "Tailwind", "ShadcnUI",
      "Clerk", "Pinecone", "Groq API", "Scraper API", "Cheerio", "HuggingFace API", "Vercel",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/Rate-My-Professor-Chatbot",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_ai-edtech-nextjs-activity-7234948272107229184-ozzs",
    image: "/projects/profeval.png",
    video: "https://www.youtube.com/embed/xS7mu37Y_8I",
    screenBg: "linear-gradient(135deg, #120820 0%, #1c1040 50%, #0c0518 100%)",
    accent: "#8B5CF6",
  },
  {
    slug: "stocksmart",
    num: "04",
    name: "StockSmart",
    tag: "Headstarter AI Project · 50+ users",
    date: "Aug 2024",
    problemSolved:
      "Built a system to help users manage stock, finances, and recipes in one place.",
    description:
      "Built real-time data updates using Firebase & Redux, integrated image-taking, and added recipe suggestion capabilities using Gemini API to assist users in managing their pantry more efficiently.",
    stack: [
      "Next.js", "Firebase", "TypeScript", "Tailwind",
      "MUI", "Clerk", "Vercel", "Gemini API",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/inventory-management-system",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_softwareengineering-fullstackdevelopment-activity-7225959154484449282-RoI2",
    image: "/projects/stocksmart.png",
    video: "https://www.youtube.com/embed/SILVcf1VU3o",
    screenBg: "linear-gradient(135deg, #1a1000 0%, #2a1a00 50%, #120c00 100%)",
    accent: "#F59E0B",
  },
  {
    slug: "cardhunt",
    num: "05",
    name: "CardHunt",
    tag: "Headstarter AI Project",
    date: "Aug 2024",
    problemSolved:
      "Developed a platform to help users of all backgrounds connect and discover AI-powered flashcards.",
    description:
      "Built an AI-powered flashcard generation system where users can create detailed flashcards, engage with the community through comments and upvotes, and track post analytics on a dashboard.",
    stack: [
      "PostgreSQL", "Prisma", "OpenRouter API", "Next.js",
      "TypeScript", "Tailwind", "ShadcnUI", "Framer Motion", "NextAuth", "Vercel",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/CardHunt",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_ai-edtech-nextjs-activity-7231412311339507714-hU2P",
    image: "/projects/cardhunt.png",
    video: "https://www.youtube.com/embed/G-zUYSAr-ec",
    screenBg: "linear-gradient(135deg, #200818 0%, #380d28 50%, #180610 100%)",
    accent: "#EC4899",
  },
  {
    slug: "crime-script-nlp",
    num: "06",
    name: "Crime Script NLP",
    tag: "Research Project · Network Security",
    date: "Jan 2026",
    problemSolved:
      "Reimplemented and enhanced an NLP pipeline for crime script analysis of scams, addressing gaps in semantic accuracy and data security in the original research.",
    description:
      "Enhanced the pipeline with Sentence Transformer embeddings for richer semantic analysis, end-to-end AES-256-CBC encryption with RSA-OAEP key exchange, HMAC-SHA256 integrity verification, replay attack prevention, and an attack simulation module. Collaborated in a team of 3.",
    stack: [
      "Python", "Sentence Transformers", "NLP", "AES-256-CBC", "RSA-OAEP",
      "HMAC-SHA256", "scikit-learn", "NLTK", "Clustering", "Git",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/AimenMunawarDeveloper/Crime-Script-Analysis-Using-NLP",
    details: "https://www.linkedin.com/posts/aimen-munawar-235852247_i-wanted-to-share-a-project-we-worked-on-ugcPost-7413918005589573632-C9SS",
    image: "/projects/crime-script-nlp.png",
    video: "https://www.youtube.com/embed/52Ycx57Ubck",
    screenBg: "linear-gradient(135deg, #1a0505 0%, #2d0a0a 50%, #110303 100%)",
    accent: "#EF4444",
  },
  {
    slug: "vynx",
    num: "07",
    name: "Vynx",
    tag: "Cloud Computing Project · SE-315",
    date: "2025",
    problemSolved:
      "Built a scalable short video streaming platform using microservices to explore cloud-native deployment patterns and distributed system design.",
    description:
      "Built with a microservices architecture deployed on GCP using Cloud Run and Docker. Integrated Firebase Authentication, Cloudinary for video hosting with storage limits and alerts, bandwidth tracking, and API request logging. Developed in a team of 4.",
    stack: [
      "Next.js", "Tailwind", "Firebase Auth", "Cloudinary",
      "GCP", "Cloud Run", "Docker", "Microservices",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/Cloud-Computing-Project",
    details: "https://www.linkedin.com/posts/aimen-munawar-235852247_vynx-demo-activity-7294993345875984384-udk2",
    image: "/projects/vynx.png",
    video: "https://www.loom.com/embed/0b2aff6cfdd542d19d47c0f54ae36ac3",
    screenBg: "linear-gradient(135deg, #020d18 0%, #041a2e 50%, #010c16 100%)",
    accent: "#06B6D4",
  },
  {
    slug: "spidex",
    num: "08",
    name: "Spidex",
    tag: "Headstarter Hiring Hackathon 1 · 100+ users",
    date: "Aug 2024",
    problemSolved:
      "Developed a web scraper to help users efficiently extract, analyze, and store web data at scale.",
    description:
      "Built an automated web scraping system where users extract and store large volumes of data in JSON, HTML, or plain text formats using a customizable scraping algorithm. Features Clerk authentication and persistent scrape history. Developed in a team of 5.",
    stack: [
      "Node.js", "Cheerio", "PrismJS", "MongoDB", "Next.js",
      "TypeScript", "Tailwind", "Clerk", "Vercel",
    ],
    achievement: "Finalist · Olostep Track · Headstarter Hackathon 1",
    achievements: ["Finalist · Olostep Track · Headstarter Hackathon 1"],
    github: "https://github.com/kambohdiv/Olostep-webscraper",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_webscraping-hackathon-nextjs-activity-7231049319917731841-541m",
    image: "/projects/spidex.png",
    video: "https://www.youtube.com/embed/NHBeAQMFWsI",
    screenBg: "linear-gradient(135deg, #0e0800 0%, #1e1200 50%, #080500 100%)",
    accent: "#F97316",
  },
  {
    slug: "assist-ai",
    num: "09",
    name: "Assist AI",
    tag: "Headstarter AI Project",
    date: "Aug 2024",
    problemSolved:
      "Built a customizable AI-powered customer support chatbot platform for businesses, enabling real-time personalized assistance and interaction analytics.",
    description:
      "Built with Gemini API for multi-turn intelligent conversations, a customizable knowledge base per business, real-time session analytics for admins, and persistent chat history via cookies. Developed in a team of 4.",
    stack: [
      "Next.js", "TypeScript", "Tailwind", "ShadCN UI", "DaisyUI",
      "Neon PostgreSQL", "GraphQL", "StepZen", "IBM API Connect", "Clerk", "Vercel", "Gemini API",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/AI-customer-assistance",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_softwareengineering-fullstackdevelopment-activity-7228507196605513728-DNxD",
    image: "/projects/assist-ai.png",
    video: "https://www.youtube.com/embed/AB0rmxWoKZg",
    screenBg: "linear-gradient(135deg, #08021a 0%, #130530 50%, #050112 100%)",
    accent: "#7C3AED",
  },
  {
    slug: "smartdocs",
    num: "10",
    name: "SmartDocs",
    tag: "Headstarter AI Hackathon · 100+ users",
    date: "Jul 2024",
    problemSolved:
      "Addressed limitations of traditional document editors by adding real-time multi-user collaboration, a robust commenting system, and integrated AI writing assistance.",
    description:
      "Built a Google Docs-like collaborative editor with Liveblocks for real-time sync, Gemini API for AI writing assistance, Clerk for authentication, and Sentry for performance monitoring. Developed in a team of 4.",
    stack: [
      "Next.js", "React", "TypeScript", "Tailwind", "ShadcnUI",
      "Liveblocks", "Clerk", "Gemini API", "Sentry", "Vercel",
    ],
    achievement: "Top 20 Teams · 48-hour Hackathon",
    achievements: ["Top 20 Teams · 48-hour Hackathon"],
    github: "https://github.com/javeria2108/SmartDocs",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_hackathon-smartdocs-ai-activity-7223309324415098880-7gic",
    image: "/projects/smartdocs.png",
    video: "https://www.youtube.com/embed/npgJXWY1jSE",
    screenBg: "linear-gradient(135deg, #020c1e 0%, #041830 50%, #010910 100%)",
    accent: "#2563EB",
  },
  {
    slug: "datahub",
    num: "11",
    name: "DataHub",
    tag: "DPL Internship Project",
    date: "Jun 2024",
    problemSolved:
      "Built a full-stack file management system combining Google Drive-style uploads with an admin analytics dashboard, replacing fragmented workflows with a single platform.",
    description:
      "Implemented secure file handling via AWS S3, Bcrypt-hashed authentication with JWT tokens, a personal storage page with file CRUD, monthly/weekly upload graphs, dynamic profile photo with color-matched header via Cloudinary.",
    stack: [
      "React", "TypeScript", "Tailwind", "Redux", "Node.js",
      "Express", "MongoDB", "AWS S3", "Cloudinary", "Vercel", "Heroku",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/DataHub",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_excited-to-share-my-latest-project-datahub-activity-7210630278006923264-v1W5",
    image: "/projects/datahub.png",
    video: "https://www.youtube.com/embed/3nPC1hVMlnY",
    screenBg: "linear-gradient(135deg, #021208 0%, #041f0e 50%, #010b05 100%)",
    accent: "#10B981",
  },
  {
    slug: "greenthread",
    num: "12",
    name: "GreenThread",
    tag: "Database Systems Project",
    date: "Nov 2023 – Jan 2024",
    problemSolved:
      "Raised awareness on sustainable fashion by building an ecommerce marketplace to showcase and market local sustainable brands in one place.",
    description:
      "Full-stack MERN ecommerce platform with an admin dashboard for product, blog, coupon, and user management; order analytics; customer support tooling; and Cloudinary for image handling. Developed in a team of 3.",
    stack: [
      "React", "Node.js", "Express", "MongoDB", "Redux Toolkit",
      "Cloudinary", "Netlify", "Git",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/mkhan429419/GreenThread",
    details: "https://www.linkedin.com/posts/maheen-akhtar-khan-377082267_greenthread-im-thrilled-to-share-activity-7210620710925312000-Cku7",
    image: "/projects/greenthread.png",
    video: null,
    screenBg: "linear-gradient(135deg, #061202 0%, #0c2004 50%, #030c01 100%)",
    accent: "#84CC16",
  },
  {
    slug: "searchify",
    num: "13",
    name: "Searchify",
    tag: "DSA Project",
    date: "Nov 2023 – Dec 2023",
    problemSolved:
      "Built a prototype search engine inspired by Google's architecture to demonstrate core information retrieval concepts — crawling, indexing, and relevance ranking.",
    description:
      "Deployed on the NELA-GT 2022 dataset (100,000 articles) with forward and inverted indexes, BM-25F and Cosine Similarity ranking algorithms, support for single and multi-word queries, dynamic content addition, and a Django frontend. Developed in a team of 3.",
    stack: [
      "Python", "Django", "scikit-learn", "NLTK", "BM-25F",
      "Cosine Similarity", "NELA-GT 2022", "Git",
    ],
    achievement: null,
    achievements: [],
    github: "https://github.com/tehreemahmad149/DSAProject",
    details: "https://www.linkedin.com/posts/umair-gosal-227b54201_hi-linkedin-fam-in-collaboration-with-ugcPost-7166062280969764864-NOFk",
    image: "/projects/searchify.png",
    video: "https://www.youtube.com/embed/1-5im1gsidk",
    screenBg: "linear-gradient(135deg, #06040e 0%, #0e0820 50%, #040309 100%)",
    accent: "#6366F1",
  },
];

export type Project = (typeof projects)[0];
